# @package data

########################################################################
# General Camera Settings 
########################################################################

camera_dist: 4.0
camera_width: 256
camera_height: 256
camera_focal: 512
camera_sphere_eps: 1e-1

########################################################################
# Preprocess Mesh 
########################################################################

preprocess_mesh:
  _target_: lib.data.preprocess.PreprocessMesh
  _partial_: True
  data_dir: ${data.data_dir}
  skip: True
  resolution: 30000
  laplacian_num_iters: 1

########################################################################
# Preprocessing Synthetic 
########################################################################

preprocess_synthetic:
  _target_: lib.data.preprocess.PreprocessSynthetic
  _partial_: True
  # processing settings
  data_dir: ${data.data_dir}
  skip: True
  # camera settings
  azims: [0, 20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240, 260, 280, 300, 320, 340]
  elevs: [-50, -30, -10, 10, 30]
  dist: ${data.camera_dist} 
  width: ${data.camera_width} 
  height: ${data.camera_height} 
  focal: ${data.camera_focal} 
  sphere_eps: ${data.camera_sphere_eps} 
  # sketch settings
  t_lower: 100
  t_upper: 150
  aperture_size: 3  # 3, 5, 7
  l2_gradient: True

########################################################################
# Preprocessing Renderings
########################################################################

preprocess_renderings:
  _target_: lib.data.preprocess.PreprocessRenderings
  _partial_: True
  # processing settings
  data_dir: ${data.data_dir}
  deepsdf_ckpt_path: ${deepsdf_ckpt_path} 
  skip: True
  split: ???
  # traversal settings
  traversal: False
  n_renderings: 10
  t_mean: 0.25
  t_std: 0.1
  # camera settings
  azims: [-90.0, -45.0, 0.0, 45.0, 90.0]
  azim_std: 22.5
  elev: -20.0
  elev_std: 5.0
  dist: ${data.camera_dist} 
  width: ${data.camera_width} 
  height: ${data.camera_height} 
  focal: ${data.camera_focal} 
  sphere_eps: ${data.camera_sphere_eps} 
  # grayscale settings
  ambient: 0.2
  diffuse: 0.5
  # sketch settings
  t_lower: 100
  t_upper: 150
  aperture_size: 3  # 3, 5, 7
  l2_gradient: True

########################################################################
# Preprocessing SDF
########################################################################

preprocess_sdf:
  _target_: lib.data.preprocess.PreprocessSDF
  _partial_: True
  # processing settings
  data_dir: ${data.data_dir}
  skip: True
  # sample surface points
  surface_samples: 50000
  # sample near points
  near_samples_1: 100000
  near_scale_1: 5e-03
  near_buffer_1: 1.1
  # sample near points
  near_samples_2: 100000
  near_scale_2: 5e-02
  near_buffer_2: 1.1
  # sample unit sphere points
  unit_samples: 50000
  unit_buffer: 2.0