# @package _global_

defaults:
  - data:
    - optimize_latent
  - model: optimize_latent
  - trainer: default
  - logger: default
  - hydra: default
  - paths: default
  - debug: null
  - optional local: default
  - _self_

seed: 123
task_name: optimize_normals
tags: ["optimize_normals"]
split: val
obj_ids: ???
train: True
prior_idx: mean  # random(-2), mean(-1), prior, prior(idx)
eval: True
save_mesh: True
create_video: True
ckpt_path: ???

trainer:
  num_sanity_val_steps: 0
  max_epochs: 15
  accumulate_grad_batches: 4

data:
  train_dataset:
    _target_: lib.data.deepsdf_dataset.NormalLatentOptimizerDataset
    azims: ${data.preprocess_siamese.azims}
    elevs: ${data.preprocess_siamese.elevs}
  shuffle: True

model:
  _target_: lib.models.optimize_normals.DeepSDFNormalRender
  reg_weight: 1e-01
  video_capture_rate: 8
  optimizer:
    lr: 5e-03
  scheduler:
    step_size: 5
    gamma: 0.5
  c2f_scheduler:
    _target_: lib.data.scheduler.Coarse2FineScheduler
    resolution: ${model.image_resolution}
    max_epochs: ${trainer.max_epochs}
    milestones: [5, 10] 
