# @package _global_

defaults:
  - data: train_deepsdf 
  - dataset: shapenet_chair_4096
  - model: deepsdf
  - callbacks: default
  - logger: default 
  - trainer: default
  - hydra: default
  - paths: default
  - optional local: default
  - experiement: null
  - debug: null
  - _self_

seed: 123
task_name: train_deepsdf
tags: ["train_deepsdf"]
train: True
ckpt_path: ???
deepsdf_ckpt_path: ???
loss_ckpt_path: ???
