# @package model
_target_: lib.models.deepsdf.DeepSDF

latent_size: 512
num_hidden_layers: 8
latent_vector_size: 256
num_latent_vectors: ${data.num_obj_train}
clamp: True
clamp_val: 0.1
reg_loss: True
reg_weight: 1e-04
skip_connection: [4]
dropout: 0.2
weight_norm: True

loss:
  _target_: torch.nn.L1Loss
  _partial_: true
  reduction: mean

decoder_optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 5e-04

latents_optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-03