# @package model

# custom settings
_target_: lib.models.loss.LatentLoss
support_latent: True

# base settings
embedding_size: 256
pretrained: True 
shared: False
head: linear
mode: cosine
lr_head: 1e-03
lr_backbone: 1e-05
scheduler: null
