# @package model

_target_: lib.models.optimize_deepsdf.DeepSDFLatentOptimizer
ckpt_path: ${ckpt_path} 
prior_idx: -1
reg_loss: True
reg_weight: 1e-05
step_scale: 1.0
image_resolution: 256
mesh_resolution: 256
mesh_chunk_size: 65536
video_capture_rate: 30
video_azim: 40 
video_elev: -30
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-02
scheduler:
  _partial_: True
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 100
  gamma: 0.5