# @package model

_target_: lib.eval.traverse_latent.LatentTraversal
# base settings
data_dir: ${data.data_dir}
loss_ckpt_path: ${loss_ckpt_path} 
deepsdf_ckpt_path: ${deepsdf_ckpt_path}
compute_loss: ${compute_loss} 
# init settings: random, mean, prior, prior(idx), retrieval, latent
source_latent_init: random
source_obj_id: ""
# init settings: random, mean, prior, prior(idx), retrieval, latent
target_latent_init: random
target_obj_id: ""
# mesh settings
create_mesh: ${create_mesh}
create_video: ${create_video}
mesh_resolution: 128
mesh_chunk_size: 65536
# rendering settings
capture_rate: 30
n_render_steps: 100
clamp_sdf: 0.1
step_scale: 1.0
surface_eps: 1e-03
sphere_eps: 1e-01
normal_eps: 5e-03